spring:
  application:
    name: contract-platform-api
  profiles:
    default: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/contracts}
    username: ${DB_USER:contracts}
    password: ${DB_PASSWORD:contracts}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    tags:
      application: contract-platform-api
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [corr:%X{correlationId:-none}]"
  level:
    root: INFO
    ru.vkr.contracts: INFO

security:
  users:
    admin:
      username: ${SECURITY_ADMIN_USERNAME}
      password: ${SECURITY_ADMIN_PASSWORD}
    developer:
      username: ${SECURITY_DEVELOPER_USERNAME}
      password: ${SECURITY_DEVELOPER_PASSWORD}
    viewer:
      username: ${SECURITY_VIEWER_USERNAME}
      password: ${SECURITY_VIEWER_PASSWORD}

generation:
  jobs:
    retry:
      max-attempts: 3
      backoff-ms: 500
    recovery:
      enabled: true
      stale-threshold-ms: 600000
      scan-interval-ms: 60000
  open-api:
    group-id: ${GEN_OPENAPI_GROUP_ID:ru.vkr.contracts.generated}
    artifact-suffix: ${GEN_OPENAPI_ARTIFACT_SUFFIX:rest-client}
    nexus:
      base-url: ${NEXUS_BASE_URL:http://localhost:8081}
      repository: ${NEXUS_REPOSITORY:maven-releases}
      username: ${NEXUS_USERNAME:}
      password: ${NEXUS_PASSWORD:}
  async-api:
    group-id: ${GEN_ASYNCAPI_GROUP_ID:ru.vkr.contracts.generated}
    artifact-suffix: ${GEN_ASYNCAPI_ARTIFACT_SUFFIX:kafka-lib}
    nexus:
      base-url: ${NEXUS_BASE_URL:http://localhost:8081}
      repository: ${NEXUS_REPOSITORY:maven-releases}
      username: ${NEXUS_USERNAME:}
      password: ${NEXUS_PASSWORD:}
    schema-registry:
      base-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
      username: ${SCHEMA_REGISTRY_USERNAME:}
      password: ${SCHEMA_REGISTRY_PASSWORD:}
      compatibility: ${SCHEMA_REGISTRY_COMPATIBILITY:BACKWARD}
      schema-type: ${SCHEMA_REGISTRY_SCHEMA_TYPE:AVRO}
      subject-suffix: ${SCHEMA_REGISTRY_SUBJECT_SUFFIX:value}
